name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: "*.sh"
